main: nexus.slime.deathsentence.DeathSentencePlugin
api-version: '1.13'

name: DeathSentence
description: An improved death messages plugin that tries to give as much control as possible, while providing reasonable fallbacks.
version: $version
authors:
  - "Rodney_Mc_Kay"
  - "Gizer"

commands:
  deathsentence:
    usage: "/deathsentence <generate_full_config|reload>"
    permission: deathsentence.admin
    description: Command to configure settings for the death sentence plugin
